### ISSUE TITLE
Functions directory launch `npm start` encountered UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by FeynmanDNA** [NUS-ALSET/achievements#448]
I obtained the serviceAccountKey.json from achievements-dev firebase console, and implemented the following code in:
```javascript
const serviceAccount = require("./config/serviceAccountKey.json");

admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
  databaseURL: "https://achievements-dev.firebaseio.com"
});
```
And I created a directory called `config/` in the functions folder and put the serviceAccountKey.json inside:
![image](https://user-images.githubusercontent.com/26617036/45864194-c495a980-bdab-11e8-83c9-fce9c884c926.png)

However, when I run `npm start` in the functions folder, I received the following error from node:
```shell
$: ~/achievements-my-local/functions$ npm start

> functions@ start /home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions
> firebase serve --only functions & node ./localTriggers.js

(node:18634) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:18634) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18634) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Request failed with status code 502

=== Serving from '/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local'...


Error: An unexpected error has occurred.
Request failed with status code 502
Request failed with status code 502
Request failed with status code 502
```

I basically followed the tutorial from firebase-admin SDK (https://firebase.google.com/docs/admin/setup), the serviceAccountKey.json is obtained from achievements-dev firebase console, and the code snippets are exactly the same as the ones shown in the tutorial. So I am wondering what is causing the error here?

**Comment by Brainenjii** [comment]
could you reproduce this issue?

**Comment by FeynmanDNA** [comment]
@Brainenjii If I use the code from #449 then yes. I still get the same error.

But i also noticed that now the jupyterInline activities get executed! Did you just start the local npm start of functions on your side?

**Comment by Brainenjii** [comment]
yeah, I just tried it and I didn't get any errors

**Comment by Brainenjii** [comment]
hm, no, it was supposed to use any amount of serviceAccountKeys. I thought 404 error could occur if there is a request to the wrong URL at HTTP queue

**Comment by FeynmanDNA** [comment]
i tried again, and i will get the UnhandlePromiseRejectionWarning: Error:
```shell
(node:21866) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21866) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:21866) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by FeynmanDNA** [comment]
hi, i removed the node_modules and pack-lock.json and ran `npm install`

now `npm start` does not have the 404 warnings anymore!

but i still have this message;
```shell
$ npm start

> functions@ start /home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions
> firebase serve --only functions & node ./localTriggers.js


=== Serving from '/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local'...


Error: An unexpected error has occurred.
```

**Comment by FeynmanDNA** [comment]
sorry, the 404 UnhandledPromiseRejectionWarning is still there... after a few seconds it appears:
```
=== Serving from '/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local'...


Error: An unexpected error has occurred.
(node:21998) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local/functions/node_modules/axios/lib/adapters/http.js:192:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:21998) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:21998) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by Brainenjii** [comment]
ok, we have to check all axios calls and find `unprotected` axios calls. At glance I found these ones:
https://github.com/NUS-ALSET/achievements/blob/master/functions/src/updateProfile.js#L11
Maybe it source of all warnings

**Comment by FeynmanDNA** [comment]
wow, awesome! But I am curious how were we able to run the functions npm start locally on your side previously without having this 404 issue?

**Comment by Brainenjii** [comment]
that's strange. Could you apply this patch at local and re-run `npm start`?
```
Index: functions/src/updateProfile.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- functions/src/updateProfile.js	(date 1537449503000)
+++ functions/src/updateProfile.js	(date 1537515688000)
@@ -103,7 +103,8 @@
             })
 
             .then(() => resolve())
-        );
+        )
+        .catch(err => console.error(err.message));
     default:
       return Promise.resolve();
   }
```

**Comment by FeynmanDNA** [comment]
![image](https://user-images.githubusercontent.com/26617036/45867781-ce70da00-bdb6-11e8-8e30-c29360e1c1f7.png)

![image](https://user-images.githubusercontent.com/26617036/45867772-c87af900-bdb6-11e8-83c5-8c4df8cdc358.png)

I was waiting for more error message to appear, but looks like that is all the terminal returns.

**Comment by Brainenjii** [comment]
could you also run separately `node ./localTriggers` and `firebase serve --only functions`? I got no errors on the first and and error with the 2nd one

**Comment by FeynmanDNA** [comment]
I got the following errors:

```shell
$ node ./localTriggers.js 
Request failed with status code 404
^C

$ firebase serve --only functions

=== Serving from '/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local'...


Error: An unexpected error has occurred.
```

**Comment by Brainenjii** [comment]
could you check firebase instances? Mb you already have some launched? E.g. `ps ax|grep firebase`

**Comment by FeynmanDNA** [comment]
can this be the reason (from firebase-debug.log):
```
[info] === Serving from '/home/tanuki/Documents/Work/NUS-ALSET/achievements-my-local'...
[info] 
[debug] [2018-09-12T10:20:25.366Z] Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/logs'
    at Object.mkdirSync (fs.js:729:3)
    at Object.assertLogsPath (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/emulator/logs.js:65:10)
    at new Controller (/usr/lib/node_modules/firebase-tools/node_modules/@google-cloud/functions-emulator/src/cli/controller.js:77:32)
    at FunctionsEmulator.start (/usr/lib/node_modules/firebase-tools/lib/functionsEmulator.js:113:21)
    at Object.start (/usr/lib/node_modules/firebase-tools/lib/serve/functions.js:9:29)
    at /usr/lib/node_modules/firebase-tools/lib/serve/index.js:17:21
    at arrayMap (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:639:23)
    at Function.map (/usr/lib/node_modules/firebase-tools/node_modules/lodash/lodash.js:9554:14)
    at _serve (/usr/lib/node_modules/firebase-tools/lib/serve/index.js:15:7)
    at Command._action (/usr/lib/node_modules/firebase-tools/commands/serve.js:48:12)
[error] 
[error] Error: An unexpected error has occurred.
```

**Comment by Brainenjii** [comment]
oh. I got my `node.js` installed from `nvm` it provides global modules installed in my user dir. Could you run `npm install firebase-tools` in `./functions` dir?

**Comment by FeynmanDNA** [comment]
hi, after install firebase-tools in functions, i got the following now with `npm start`:
![image](https://user-images.githubusercontent.com/26617036/45868936-9dde6f80-bdb9-11e8-9653-8d421abde647.png)

Does this mean I have now launched my own local functions?

**Comment by Brainenjii** [comment]
yeah, you got all `https` triggers now. Unfortunately, it  doesn't start database triggers and you still need localTriggers for them.
Btw, I also got this 404 warning after some time of launched localTriggers. I'll try figure out why it fires all the time

**Comment by FeynmanDNA** [comment]
sometimes `npm start` gets all the functions running, but most of the time I get `error: code=500` for some of the functions:
```
✔  functions: handleProfileQueue: http://localhost:5000/achievements-dev/us-central1/handleProfileQueue
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
```
or
```
✔  functions: downloadEvents: http://localhost:5000/achievements-dev/us-central1/downloadEvents
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
✔  functions: api: http://localhost:5000/achievements-dev/us-central1/api
⚠  functions: Error from emulator. [object Object]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]
```

What is causing this `error:  code=500, status=INTERNAL, message=Function worker killed by signal: SIGTERM, errors=[Function worker killed by signal: SIGTERM]` message for various functions?

**Comment by Brainenjii** [comment]
I also got this errors from time to time. I think it could be on too often relaunch but it isn't exactly

**Comment by FeynmanDNA** [comment]
thanks so much for the communication! cheers
